// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleDetail: typeof import('./src/components/ArticleDetail.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ArticleMeta: typeof import('./src/components/ArticleMeta.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    Header: typeof import('./src/components/Header.vue')['default']
    MainEditor: typeof import('./src/components/MainEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ztransition: typeof import('./src/components/Ztransition.vue')['default']
  }
}

export {}
