version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - db

  backend:
    image: veditor-backend
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/realworld
    networks:
      - back
      - db

  frontend:
    image: veditor-frontend
    ports:
      - 8082:80
    depends_on:
      - backend
    networks:
      - back

networks:
  back:
  db:
